# Generated by Django 6.0.2 on 2026-02-27 00:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('USER_CREATED', 'A coach was created successfully'), ('LOGIN', 'the user logged in successfully'), ('LOGOUT', 'Logged out successfully'), ('TOKEN_REFRESH', 'Token Refeshed'), ('SESSION_SCHEDULED', 'Session scheduled successfully'), ('SESSION_COMPLETED', 'Session completed successfully'), ('SESSION_EDIT', 'Session modified successfully'), ('SESSION_DELETE', 'Session eliminated successfully'), ('CLIENT_CREATE', 'Client createed successfully'), ('CLIENT_EDIT', 'Client modified successfully'), ('CLIENT_DELETE', 'Client eliminated successfully')], max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=110, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='coach.coach')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
