# Generated by Django 6.0.2 on 2026-02-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('USER_CREATED', 'Coach Created'), ('LOGIN', 'Logged in'), ('LOGOUT', 'Logged out'), ('TOKEN_REFRESH', 'Token Refeshed'), ('SESSION_SCHEDULED', 'Session scheduled'), ('SESSION_COMPLETED', 'Session completed'), ('SESSION_EDIT', 'Session modified '), ('SESSION_DELETE', 'Session eliminated'), ('CLIENT_CREATE', 'Client created'), ('CLIENT_EDIT', 'Client modified'), ('CLIENT_DELETE', 'Client eliminated')], max_length=100),
        ),
    ]
