# Generated by Django 5.1.3 on 2026-03-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditLog', '0005_alter_auditlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
