# Generated by Django 6.0.2 on 2026-02-19 15:50

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(verbose_name=255)),
                ('last_name', models.CharField(verbose_name=255)),
                ('phone_num', models.CharField(blank=True, null=True, verbose_name=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('session_credits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_session_date', models.DateField(default=datetime.date.today)),
                ('sessions_completed', models.IntegerField(default=0)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='coach.coach')),
            ],
        ),
    ]
