# Generated by Django 6.0.2 on 2026-02-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_num',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
